# Generated by Django 5.2.11 on 2026-02-11 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0002_alter_task_difficulty_alter_task_subject"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Математика"),
                            ("geom", "Геометрия"),
                            ("d_math", "Дискретная Математика"),
                            ("phys", "Физика"),
                            ("chem", "Химия"),
                            ("bio", "Биология"),
                            ("eco", "Экология"),
                            ("geo", "География"),
                            ("astro", "Астрономия"),
                            ("rus_lang", "Русский язык"),
                            ("rus_lit", "Литература"),
                            ("eng_lang", "Английский язык"),
                            ("d_lang", "Немецкий язык"),
                            ("fr_lang", "Французский язык"),
                            ("chi_lang", "Китайский язык"),
                            ("sp_lang", "Испанский язык"),
                            ("lat_lang", "Латинский язык"),
                            ("hist", "История"),
                            ("s_st", "Обществознание"),
                            ("law", "Право"),
                            ("econ", "Экономика"),
                            ("fin_lit", "Финансовая грамотность"),
                            ("arts", "Искусство (МХК)"),
                            ("tech", "Технология"),
                            ("pc_sci", "Информатика"),
                            ("robot", "Робототехника"),
                            ("ai", "Искусственный интеллект"),
                            ("pe", "Физкультура"),
                            ("obzr", "ОБЖ"),
                        ],
                        max_length=100,
                    ),
                ),
                ("total_tasks", models.PositiveIntegerField()),
                ("task_ids", models.JSONField(default=list)),
                ("current_position", models.PositiveIntegerField(default=0)),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("is_finished", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_answer", models.CharField(max_length=255)),
                ("is_correct", models.BooleanField(default=False)),
                ("answered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_answers",
                        to="tasks.task",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="training.trainingsession",
                    ),
                ),
            ],
            options={
                "ordering": ["answered_at"],
                "unique_together": {("session", "task")},
            },
        ),
    ]
