# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


def backfill_question_data(apps, schema_editor):
    Match = apps.get_model("pvp", "Match")
    for match in Match.objects.all().only("id", "task_id", "question_task_ids", "questions_count", "current_question_index"):
        updated_fields = []

        if not match.question_task_ids:
            match.question_task_ids = [match.task_id]
            updated_fields.append("question_task_ids")

        if not match.questions_count or match.questions_count < 1:
            match.questions_count = 1
            updated_fields.append("questions_count")

        if not match.current_question_index or match.current_question_index < 1:
            match.current_question_index = 1
            updated_fields.append("current_question_index")

        if updated_fields:
            match.save(update_fields=updated_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="current_question_index",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="match",
            name="player1_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="player2_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="question_task_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="match",
            name="questions_count",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(backfill_question_data, migrations.RunPython.noop),
    ]
