# Generated by Django 5.2.11 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE pvp_match
                        ADD COLUMN IF NOT EXISTS current_question_index integer;

                        ALTER TABLE pvp_match
                        ALTER COLUMN current_question_index SET DEFAULT 1;

                        UPDATE pvp_match
                        SET current_question_index = 1
                        WHERE current_question_index IS NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN current_question_index SET NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE pvp_match
                        ALTER COLUMN current_question_index DROP NOT NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN current_question_index DROP DEFAULT;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='match',
                    name='current_question_index',
                    field=models.PositiveSmallIntegerField(default=1),
                ),
            ],
        ),
    ]
