# Generated by Django 5.2.11 on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0002_current_question_index_compat'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE pvp_match
                        ADD COLUMN IF NOT EXISTS player1_score integer;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player1_score SET DEFAULT 0;

                        UPDATE pvp_match
                        SET player1_score = 0
                        WHERE player1_score IS NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player1_score SET NOT NULL;

                        ALTER TABLE pvp_match
                        ADD COLUMN IF NOT EXISTS player2_score integer;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player2_score SET DEFAULT 0;

                        UPDATE pvp_match
                        SET player2_score = 0
                        WHERE player2_score IS NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player2_score SET NOT NULL;
                    """,
                    reverse_sql="""
                        ALTER TABLE pvp_match
                        ALTER COLUMN player1_score DROP NOT NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player1_score DROP DEFAULT;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player2_score DROP NOT NULL;

                        ALTER TABLE pvp_match
                        ALTER COLUMN player2_score DROP DEFAULT;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='match',
                    name='player1_score',
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name='match',
                    name='player2_score',
                    field=models.PositiveIntegerField(default=0),
                ),
            ],
        ),
    ]
