# Generated by Django 5.2.11 on 2026-03-03

from django.db import migrations, models


def backfill_match_options(apps, schema_editor):
    Match = apps.get_model("pvp", "Match")
    for match in Match.objects.all().only(
        "id",
        "status",
        "started_at",
        "created_at",
        "timer_enabled",
        "time_limit_seconds",
        "current_question_started_at",
    ):
        update_fields = []

        if match.timer_enabled and not match.time_limit_seconds:
            match.time_limit_seconds = 600
            update_fields.append("time_limit_seconds")

        if match.status == "active" and not match.current_question_started_at:
            match.current_question_started_at = match.started_at or match.created_at
            update_fields.append("current_question_started_at")

        if update_fields:
            match.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("pvp", "0002_match_questions_and_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="current_question_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="hints_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="match",
            name="private_token",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="match",
            name="random_order",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="match",
            name="time_limit_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="timer_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(backfill_match_options, migrations.RunPython.noop),
    ]
