# Generated by Django 5.2.11 on 2026-03-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pvp', '0003_player_scores_compat'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DO $$
                DECLARE
                    r RECORD;
                    default_expr TEXT;
                BEGIN
                    FOR r IN
                        SELECT
                            a.attname AS col_name,
                            t.typname AS type_name,
                            format_type(a.atttypid, a.atttypmod) AS type_sql
                        FROM pg_attribute a
                        JOIN pg_class c
                            ON c.oid = a.attrelid
                        JOIN pg_namespace n
                            ON n.oid = c.relnamespace
                        JOIN pg_type t
                            ON t.oid = a.atttypid
                        LEFT JOIN pg_attrdef d
                            ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                        WHERE c.relname = 'pvp_match'
                          AND n.nspname = current_schema()
                          AND a.attnum > 0
                          AND NOT a.attisdropped
                          AND a.attnotnull
                          AND d.adbin IS NULL
                          AND a.attname NOT IN (
                              'id',
                              'player1_id',
                              'player2_id',
                              'status',
                              'created_at',
                              'started_at',
                              'finished_at',
                              'task_id',
                              'player1_answer',
                              'player2_answer',
                              'player1_submitted_at',
                              'player2_submitted_at',
                              'player1_correct',
                              'player2_correct',
                              'current_question_index',
                              'player1_score',
                              'player2_score'
                          )
                    LOOP
                        default_expr := NULL;

                        IF r.type_name = 'bool' THEN
                            default_expr := 'false';
                        ELSIF r.type_name IN ('int2', 'int4', 'int8', 'numeric', 'float4', 'float8') THEN
                            default_expr := '0';
                        ELSIF r.type_name IN ('text', 'varchar', 'bpchar') THEN
                            default_expr := quote_literal('');
                        ELSIF r.type_name IN ('json', 'jsonb') THEN
                            default_expr := quote_literal('[]') || '::' || r.type_sql;
                        ELSIF left(r.type_name, 1) = '_' THEN
                            default_expr := quote_literal('{}') || '::' || r.type_sql;
                        ELSIF r.type_name IN ('timestamp', 'timestamptz') THEN
                            default_expr := 'now()';
                        ELSIF r.type_name = 'date' THEN
                            default_expr := 'CURRENT_DATE';
                        ELSIF r.type_name IN ('time', 'timetz') THEN
                            default_expr := 'CURRENT_TIME';
                        ELSIF r.type_name = 'uuid' THEN
                            default_expr := quote_literal('00000000-0000-0000-0000-000000000000') || '::uuid';
                        END IF;

                        IF default_expr IS NULL THEN
                            CONTINUE;
                        END IF;

                        EXECUTE format(
                            'UPDATE pvp_match SET %I = %s WHERE %I IS NULL',
                            r.col_name,
                            default_expr,
                            r.col_name
                        );

                        EXECUTE format(
                            'ALTER TABLE pvp_match ALTER COLUMN %I SET DEFAULT %s',
                            r.col_name,
                            default_expr
                        );
                    END LOOP;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
