# Generated by Django 5.2.10 on 2026-01-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('hints', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
