# Generated by Django 5.2.11 on 2026-02-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='subject',
            field=models.CharField(choices=[('math', 'Математика'), ('geom', 'Геометрия'), ('d_math', 'Дискретная Математика'), ('phys', 'Физика'), ('chem', 'Химия'), ('bio', 'Биология'), ('eco', 'Экология'), ('geo', 'География'), ('astro', 'Астрономия'), ('rus_lang', 'Русский язык'), ('rus_lit', 'Литература'), ('eng_lang', 'Английский язык'), ('d_lang', 'Немецкий язык'), ('fr_lang', 'Французский язык'), ('chi_lang', 'Китайский язык'), ('sp_lang', 'Испанский язык'), ('lat_lang', 'Латинский язык'), ('hist', 'История'), ('s_st', 'Обществознание'), ('law', 'Право'), ('econ', 'Экономика'), ('fin_lit', 'Финансовая грамотность'), ('arts', 'Искусство (МХК)'), ('tech', 'Технология'), ('pc_sci', 'Информатика'), ('robot', 'Робототехника'), ('ai', 'Искусственный интеллект'), ('pe', 'Физкультура'), ('obzr', 'ОБЖ')], max_length=100),
        ),
    ]
