# Generated by Django 5.2.11 on 2026-02-16 11:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='⭐', help_text='Эмодзи или короткий код иконки (напр. 🧮, 🧪, 💻)', max_length=50)),
                ('type', models.CharField(choices=[('subject', 'По предмету'), ('total', 'Общие'), ('streak', 'Серии'), ('pvp', 'PvP')], default='subject', max_length=20)),
                ('condition_subject', models.CharField(blank=True, help_text="Предмет (например: 'math', 'phys') — только для type='subject'", max_length=50, null=True)),
                ('condition_min_solved', models.PositiveIntegerField(default=0, help_text='Мин. количество решённых задач')),
                ('condition_min_correct_ratio', models.DecimalField(decimal_places=2, default=0.0, help_text='Мин. % правильных ответов (0.0–1.0)', max_digits=4)),
                ('condition_total_solved', models.PositiveIntegerField(default=0, help_text="Общее кол-во решённых задач (для type='total')")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бейдж',
                'verbose_name_plural': 'Бейджи',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Выполнено (ожидает выдачи)'), ('earned', 'Получен')], default='in_progress', max_length=20)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='badges.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бейдж пользователя',
                'verbose_name_plural': 'Бейджи пользователей',
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
